# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CariMain.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 703)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/Images/mbri-database.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 16, 16))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setGeometry(QtCore.QRect(9, 9, 991, 601))
        self.frame_main.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mdiArea = QtWidgets.QMdiArea(self.frame_main)
        self.mdiArea.setObjectName("mdiArea")
        self.subwindow_Cari_Hesap = QtWidgets.QWidget()
        self.subwindow_Cari_Hesap.setMinimumSize(QtCore.QSize(910, 300))
        self.subwindow_Cari_Hesap.setObjectName("subwindow_Cari_Hesap")
        self.frame_Cari = QtWidgets.QFrame(self.subwindow_Cari_Hesap)
        self.frame_Cari.setGeometry(QtCore.QRect(10, 10, 891, 541))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Cari.sizePolicy().hasHeightForWidth())
        self.frame_Cari.setSizePolicy(sizePolicy)
        self.frame_Cari.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_Cari.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_Cari.setObjectName("frame_Cari")
        self.tabWidget_Cari = QtWidgets.QTabWidget(self.frame_Cari)
        self.tabWidget_Cari.setGeometry(QtCore.QRect(11, 11, 821, 511))
        self.tabWidget_Cari.setObjectName("tabWidget_Cari")
        self.tab_CariKarti = QtWidgets.QWidget()
        self.tab_CariKarti.setObjectName("tab_CariKarti")
        self.splitter = QtWidgets.QSplitter(self.tab_CariKarti)
        self.splitter.setGeometry(QtCore.QRect(9, 31, 856, 60))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tableView_Cari_List = QtWidgets.QTableView(self.splitter)
        self.tableView_Cari_List.setMinimumSize(QtCore.QSize(0, 0))
        self.tableView_Cari_List.setMaximumSize(QtCore.QSize(16777215, 150))
        self.tableView_Cari_List.setBaseSize(QtCore.QSize(0, 0))
        self.tableView_Cari_List.setObjectName("tableView_Cari_List")
        self.groupBox_Cari_Kart = QtWidgets.QGroupBox(self.tab_CariKarti)
        self.groupBox_Cari_Kart.setGeometry(QtCore.QRect(9, 97, 851, 59))
        self.groupBox_Cari_Kart.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox_Cari_Kart.setObjectName("groupBox_Cari_Kart")
        self.widget = QtWidgets.QWidget(self.groupBox_Cari_Kart)
        self.widget.setGeometry(QtCore.QRect(11, 27, 831, 31))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_Cari_Kodu = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_Cari_Kodu.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_Cari_Kodu.setInputMask("")
        self.lineEdit_Cari_Kodu.setText("")
        self.lineEdit_Cari_Kodu.setObjectName("lineEdit_Cari_Kodu")
        self.horizontalLayout_2.addWidget(self.lineEdit_Cari_Kodu)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_Cari_Unvan = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_Cari_Unvan.setMaximumSize(QtCore.QSize(400, 16777215))
        self.lineEdit_Cari_Unvan.setObjectName("lineEdit_Cari_Unvan")
        self.horizontalLayout_2.addWidget(self.lineEdit_Cari_Unvan)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setMaximumSize(QtCore.QSize(16777215, 26))
        self.pushButton_3.setBaseSize(QtCore.QSize(0, 0))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/Images/magnifying-glass-4x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_Cari_Durumu = QtWidgets.QLabel(self.widget)
        self.label_Cari_Durumu.setObjectName("label_Cari_Durumu")
        self.horizontalLayout_2.addWidget(self.label_Cari_Durumu)
        self.comboBox_Cari_Durum = QtWidgets.QComboBox(self.widget)
        self.comboBox_Cari_Durum.setObjectName("comboBox_Cari_Durum")
        self.comboBox_Cari_Durum.addItem("")
        self.comboBox_Cari_Durum.addItem("")
        self.comboBox_Cari_Durum.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_Cari_Durum)
        self.frame = QtWidgets.QFrame(self.tab_CariKarti)
        self.frame.setGeometry(QtCore.QRect(10, 290, 851, 121))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_12.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_4.addWidget(self.lineEdit_12, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 0, 2, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_13.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_4.addWidget(self.lineEdit_13, 0, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(475, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 2, 4, 1, 1)
        self.tableView = QtWidgets.QTableView(self.frame)
        self.tableView.setObjectName("tableView")
        self.gridLayout_4.addWidget(self.tableView, 1, 1, 2, 3)
        self.frame_2 = QtWidgets.QFrame(self.tab_CariKarti)
        self.frame_2.setGeometry(QtCore.QRect(10, 170, 851, 121))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(428, 11, 416, 102))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_2.addWidget(self.lineEdit_10, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 15, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 3, 2, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 0, 4, 2, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_11.setText("")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_2.addWidget(self.lineEdit_11, 1, 1, 2, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 15, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 2, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 3, 2, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_2.addWidget(self.lineEdit_7, 2, 4, 2, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_2.addWidget(self.lineEdit_9, 3, 1, 2, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 4, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 4, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 4, 3, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_2.addWidget(self.lineEdit_6, 4, 4, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(11, 11, 413, 92))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 0, 1, 1, 4)
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 1, 1, 1, 4)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 2)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_3.addWidget(self.lineEdit_8, 2, 2, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 2, 3, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_3.addWidget(self.lineEdit_4, 2, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_CariKarti)
        self.label_6.setGeometry(QtCore.QRect(9, 9, 104, 16))
        self.label_6.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_6.setObjectName("label_6")
        self.widget1 = QtWidgets.QWidget(self.tab_CariKarti)
        self.widget1.setGeometry(QtCore.QRect(10, 420, 851, 35))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_Cari_Kart_Onceki = QtWidgets.QPushButton(self.widget1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/Images/arrow-thick-left-4x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Cari_Kart_Onceki.setIcon(icon2)
        self.pushButton_Cari_Kart_Onceki.setObjectName("pushButton_Cari_Kart_Onceki")
        self.horizontalLayout_3.addWidget(self.pushButton_Cari_Kart_Onceki)
        self.pushButton_Cari_Kart_Sonraki = QtWidgets.QPushButton(self.widget1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/Images/arrow-thick-right-4x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Cari_Kart_Sonraki.setIcon(icon3)
        self.pushButton_Cari_Kart_Sonraki.setObjectName("pushButton_Cari_Kart_Sonraki")
        self.horizontalLayout_3.addWidget(self.pushButton_Cari_Kart_Sonraki)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget1)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/Images/circle-check-4x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon4)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget1)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/Images/circle-x-4x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon5)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.tabWidget_Cari.addTab(self.tab_CariKarti, "")
        self.tab_Hesap_Hareketleri = QtWidgets.QWidget()
        self.tab_Hesap_Hareketleri.setObjectName("tab_Hesap_Hareketleri")
        self.frame_3 = QtWidgets.QFrame(self.tab_Hesap_Hareketleri)
        self.frame_3.setGeometry(QtCore.QRect(80, 160, 120, 80))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.tabWidget_Cari.addTab(self.tab_Hesap_Hareketleri, "")
        self.tab_Gorusme_Notlari = QtWidgets.QWidget()
        self.tab_Gorusme_Notlari.setObjectName("tab_Gorusme_Notlari")
        self.groupBox = QtWidgets.QGroupBox(self.tab_Gorusme_Notlari)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 671, 141))
        self.groupBox.setObjectName("groupBox")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 20, 651, 75))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.widget2 = QtWidgets.QWidget(self.groupBox)
        self.widget2.setGeometry(QtCore.QRect(10, 100, 211, 35))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Cari_Gorusme_Kaydet = QtWidgets.QPushButton(self.widget2)
        self.pushButton_Cari_Gorusme_Kaydet.setIcon(icon4)
        self.pushButton_Cari_Gorusme_Kaydet.setObjectName("pushButton_Cari_Gorusme_Kaydet")
        self.horizontalLayout.addWidget(self.pushButton_Cari_Gorusme_Kaydet)
        self.pushButton_Cari_Gorusme_Sil = QtWidgets.QPushButton(self.widget2)
        self.pushButton_Cari_Gorusme_Sil.setIcon(icon5)
        self.pushButton_Cari_Gorusme_Sil.setObjectName("pushButton_Cari_Gorusme_Sil")
        self.horizontalLayout.addWidget(self.pushButton_Cari_Gorusme_Sil)
        self.tabWidget_Cari.addTab(self.tab_Gorusme_Notlari, "")
        self.subwindow_Stok_islemleri = QtWidgets.QWidget()
        self.subwindow_Stok_islemleri.setMinimumSize(QtCore.QSize(300, 300))
        self.subwindow_Stok_islemleri.setObjectName("subwindow_Stok_islemleri")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.subwindow_Stok_islemleri)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_Stok = QtWidgets.QFrame(self.subwindow_Stok_islemleri)
        self.frame_Stok.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_Stok.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_Stok.setObjectName("frame_Stok")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_Stok)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tabWidget_Stok = QtWidgets.QTabWidget(self.frame_Stok)
        self.tabWidget_Stok.setMinimumSize(QtCore.QSize(910, 500))
        self.tabWidget_Stok.setObjectName("tabWidget_Stok")
        self.tab_Stok_Karti = QtWidgets.QWidget()
        self.tab_Stok_Karti.setObjectName("tab_Stok_Karti")
        self.groupBox_Cari_Kart_2 = QtWidgets.QGroupBox(self.tab_Stok_Karti)
        self.groupBox_Cari_Kart_2.setGeometry(QtCore.QRect(10, 100, 851, 59))
        self.groupBox_Cari_Kart_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox_Cari_Kart_2.setObjectName("groupBox_Cari_Kart_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_Cari_Kart_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(11, 27, 831, 31))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_4.addWidget(self.label_15)
        self.lineEdit_Cari_Kodu_2 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_Cari_Kodu_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_Cari_Kodu_2.setInputMask("")
        self.lineEdit_Cari_Kodu_2.setText("")
        self.lineEdit_Cari_Kodu_2.setObjectName("lineEdit_Cari_Kodu_2")
        self.horizontalLayout_4.addWidget(self.lineEdit_Cari_Kodu_2)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_4.addWidget(self.label_16)
        self.lineEdit_Cari_Unvan_2 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_Cari_Unvan_2.setMaximumSize(QtCore.QSize(400, 16777215))
        self.lineEdit_Cari_Unvan_2.setObjectName("lineEdit_Cari_Unvan_2")
        self.horizontalLayout_4.addWidget(self.lineEdit_Cari_Unvan_2)
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_6.setMaximumSize(QtCore.QSize(16777215, 26))
        self.pushButton_6.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton_6.setIcon(icon1)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_4.addWidget(self.pushButton_6)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.label_Cari_Durumu_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_Cari_Durumu_2.setObjectName("label_Cari_Durumu_2")
        self.horizontalLayout_4.addWidget(self.label_Cari_Durumu_2)
        self.comboBox_Cari_Durum_2 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_Cari_Durum_2.setObjectName("comboBox_Cari_Durum_2")
        self.comboBox_Cari_Durum_2.addItem("")
        self.comboBox_Cari_Durum_2.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_Cari_Durum_2)
        self.label_17 = QtWidgets.QLabel(self.tab_Stok_Karti)
        self.label_17.setGeometry(QtCore.QRect(10, 10, 104, 16))
        self.label_17.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_17.setObjectName("label_17")
        self.tableView_Cari_List_2 = QtWidgets.QTableView(self.tab_Stok_Karti)
        self.tableView_Cari_List_2.setGeometry(QtCore.QRect(10, 30, 856, 60))
        self.tableView_Cari_List_2.setMinimumSize(QtCore.QSize(0, 0))
        self.tableView_Cari_List_2.setMaximumSize(QtCore.QSize(16777215, 150))
        self.tableView_Cari_List_2.setBaseSize(QtCore.QSize(0, 0))
        self.tableView_Cari_List_2.setObjectName("tableView_Cari_List_2")
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab_Stok_Karti)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 450, 851, 35))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_Cari_Kart_Onceki_2 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_Cari_Kart_Onceki_2.setIcon(icon2)
        self.pushButton_Cari_Kart_Onceki_2.setObjectName("pushButton_Cari_Kart_Onceki_2")
        self.horizontalLayout_7.addWidget(self.pushButton_Cari_Kart_Onceki_2)
        self.pushButton_Cari_Kart_Sonraki_2 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_Cari_Kart_Sonraki_2.setIcon(icon3)
        self.pushButton_Cari_Kart_Sonraki_2.setObjectName("pushButton_Cari_Kart_Sonraki_2")
        self.horizontalLayout_7.addWidget(self.pushButton_Cari_Kart_Sonraki_2)
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_7.setIcon(icon4)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_7.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_8.setIcon(icon5)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_7.addWidget(self.pushButton_8)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.tabWidget_Stok.addTab(self.tab_Stok_Karti, "")
        self.tab_Stok_Ilave = QtWidgets.QWidget()
        self.tab_Stok_Ilave.setObjectName("tab_Stok_Ilave")
        self.tabWidget_Stok.addTab(self.tab_Stok_Ilave, "")
        self.horizontalLayout_6.addWidget(self.tabWidget_Stok)
        self.horizontalLayout_5.addWidget(self.frame_Stok)
        self.verticalLayout_2.addWidget(self.mdiArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 24))
        self.menubar.setObjectName("menubar")
        self.menuFirma = QtWidgets.QMenu(self.menubar)
        self.menuFirma.setObjectName("menuFirma")
        self.menuUygulama_Yonetimi = QtWidgets.QMenu(self.menubar)
        self.menuUygulama_Yonetimi.setObjectName("menuUygulama_Yonetimi")
        self.menuYardim = QtWidgets.QMenu(self.menubar)
        self.menuYardim.setObjectName("menuYardim")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionFirma_Sec = QtWidgets.QAction(MainWindow)
        self.actionFirma_Sec.setObjectName("actionFirma_Sec")
        self.actionFirma_Kapat = QtWidgets.QAction(MainWindow)
        self.actionFirma_Kapat.setObjectName("actionFirma_Kapat")
        self.action_Cik = QtWidgets.QAction(MainWindow)
        self.action_Cik.setObjectName("action_Cik")
        self.actionKullanici_islemleri = QtWidgets.QAction(MainWindow)
        self.actionKullanici_islemleri.setObjectName("actionKullanici_islemleri")
        self.actionFirma_islemleri = QtWidgets.QAction(MainWindow)
        self.actionFirma_islemleri.setObjectName("actionFirma_islemleri")
        self.actionGenel_Tanimlamalar = QtWidgets.QAction(MainWindow)
        self.actionGenel_Tanimlamalar.setObjectName("actionGenel_Tanimlamalar")
        self.actionGenel_Yardim = QtWidgets.QAction(MainWindow)
        self.actionGenel_Yardim.setObjectName("actionGenel_Yardim")
        self.actionUygulama_Guncelleme = QtWidgets.QAction(MainWindow)
        self.actionUygulama_Guncelleme.setObjectName("actionUygulama_Guncelleme")
        self.actionLisanslama = QtWidgets.QAction(MainWindow)
        self.actionLisanslama.setObjectName("actionLisanslama")
        self.actionYazilim_Firmasi_Hakkinda = QtWidgets.QAction(MainWindow)
        self.actionYazilim_Firmasi_Hakkinda.setObjectName("actionYazilim_Firmasi_Hakkinda")
        self.actionCari_Hesaplar = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/Images/icons8-capital-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCari_Hesaplar.setIcon(icon6)
        self.actionCari_Hesaplar.setObjectName("actionCari_Hesaplar")
        self.actionStok_islemleri = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/Images/icons8-product-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStok_islemleri.setIcon(icon7)
        self.actionStok_islemleri.setObjectName("actionStok_islemleri")
        self.actionRaporlar = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/Images/icons8-combo-chart-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRaporlar.setIcon(icon8)
        self.actionRaporlar.setObjectName("actionRaporlar")
        self.actionPencerleri_Yanyana_Sirala = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/Images/grid-three-up-6x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPencerleri_Yanyana_Sirala.setIcon(icon9)
        self.actionPencerleri_Yanyana_Sirala.setObjectName("actionPencerleri_Yanyana_Sirala")
        self.actionPencereleri_Ard_Arda_Sirala = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/Images/layers-6x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPencereleri_Ard_Arda_Sirala.setIcon(icon10)
        self.actionPencereleri_Ard_Arda_Sirala.setObjectName("actionPencereleri_Ard_Arda_Sirala")
        self.actionSonraki_Pencere = QtWidgets.QAction(MainWindow)
        self.actionSonraki_Pencere.setIcon(icon3)
        self.actionSonraki_Pencere.setObjectName("actionSonraki_Pencere")
        self.action_Onceki_Pencere = QtWidgets.QAction(MainWindow)
        self.action_Onceki_Pencere.setIcon(icon2)
        self.action_Onceki_Pencere.setObjectName("action_Onceki_Pencere")
        self.action_Cari_Gorusme_Kaydet = QtWidgets.QAction(MainWindow)
        self.action_Cari_Gorusme_Kaydet.setIcon(icon4)
        self.action_Cari_Gorusme_Kaydet.setObjectName("action_Cari_Gorusme_Kaydet")
        self.action_Cari_Gorusme_Sil = QtWidgets.QAction(MainWindow)
        self.action_Cari_Gorusme_Sil.setIcon(icon5)
        self.action_Cari_Gorusme_Sil.setObjectName("action_Cari_Gorusme_Sil")
        self.menuFirma.addAction(self.actionFirma_Sec)
        self.menuFirma.addAction(self.actionFirma_Kapat)
        self.menuFirma.addSeparator()
        self.menuFirma.addSeparator()
        self.menuFirma.addAction(self.action_Cik)
        self.menuUygulama_Yonetimi.addAction(self.actionKullanici_islemleri)
        self.menuUygulama_Yonetimi.addAction(self.actionFirma_islemleri)
        self.menuUygulama_Yonetimi.addAction(self.actionGenel_Tanimlamalar)
        self.menuYardim.addAction(self.actionGenel_Yardim)
        self.menuYardim.addAction(self.actionUygulama_Guncelleme)
        self.menuYardim.addAction(self.actionLisanslama)
        self.menuYardim.addAction(self.actionYazilim_Firmasi_Hakkinda)
        self.menubar.addAction(self.menuFirma.menuAction())
        self.menubar.addAction(self.menuUygulama_Yonetimi.menuAction())
        self.menubar.addAction(self.menuYardim.menuAction())
        self.toolBar.addAction(self.actionCari_Hesaplar)
        self.toolBar.addAction(self.actionStok_islemleri)
        self.toolBar.addAction(self.actionRaporlar)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Onceki_Pencere)
        self.toolBar.addAction(self.actionSonraki_Pencere)
        self.toolBar.addAction(self.actionPencerleri_Yanyana_Sirala)
        self.toolBar.addAction(self.actionPencereleri_Ard_Arda_Sirala)
        self.label_Cari_Durumu.setBuddy(self.comboBox_Cari_Durum)
        self.label_Cari_Durumu_2.setBuddy(self.comboBox_Cari_Durum)

        self.retranslateUi(MainWindow)
        self.tabWidget_Cari.setCurrentIndex(0)
        self.tabWidget_Stok.setCurrentIndex(0)
        self.actionPencerleri_Yanyana_Sirala.triggered.connect(self.mdiArea.tileSubWindows)
        self.actionPencereleri_Ard_Arda_Sirala.triggered.connect(self.mdiArea.cascadeSubWindows)
        self.actionSonraki_Pencere.triggered.connect(self.mdiArea.activateNextSubWindow)
        self.action_Onceki_Pencere.triggered.connect(self.mdiArea.activatePreviousSubWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Müşteri Cari Hesaplar ce Stok İşlemleri"))
        self.subwindow_Cari_Hesap.setWindowTitle(_translate("MainWindow", "Cari Hesaplar"))
        self.groupBox_Cari_Kart.setTitle(_translate("MainWindow", "Cari"))
        self.label_2.setText(_translate("MainWindow", "Kodu"))
        self.lineEdit_Cari_Kodu.setPlaceholderText(_translate("MainWindow", "Kodu"))
        self.label_3.setText(_translate("MainWindow", "Ünvanı"))
        self.lineEdit_Cari_Unvan.setPlaceholderText(_translate("MainWindow", "Ünvanı"))
        self.pushButton_3.setText(_translate("MainWindow", "Ara"))
        self.label_Cari_Durumu.setText(_translate("MainWindow", "&Durumu"))
        self.comboBox_Cari_Durum.setItemText(0, _translate("MainWindow", "Akrif"))
        self.comboBox_Cari_Durum.setItemText(1, _translate("MainWindow", "Pasif"))
        self.comboBox_Cari_Durum.setItemText(2, _translate("MainWindow", "Kara Listede"))
        self.label_12.setText(_translate("MainWindow", "Vergi Dairesi"))
        self.label_13.setText(_translate("MainWindow", "Vergi No"))
        self.label_14.setText(_translate("MainWindow", "Bankalar"))
        self.label_10.setText(_translate("MainWindow", "internet adresi"))
        self.label_5.setText(_translate("MainWindow", "Yetkili"))
        self.label_11.setText(_translate("MainWindow", "e-iş Kodu"))
        self.label_7.setText(_translate("MainWindow", "Telefon"))
        self.label_9.setText(_translate("MainWindow", "Posta Kodu"))
        self.label_8.setText(_translate("MainWindow", "e-mail"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Adres-1"))
        self.label.setText(_translate("MainWindow", "Adres"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Adres-2"))
        self.label_4.setText(_translate("MainWindow", "Ülke/İl/İlçe"))
        self.lineEdit_8.setPlaceholderText(_translate("MainWindow", "Ülke"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "İli"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "İlçesi"))
        self.label_6.setText(_translate("MainWindow", "Cari Hesap Listesi"))
        self.pushButton_Cari_Kart_Onceki.setText(_translate("MainWindow", "Önceki Kayıt"))
        self.pushButton_Cari_Kart_Sonraki.setText(_translate("MainWindow", "Sonraki Kayıt"))
        self.pushButton_4.setText(_translate("MainWindow", "Kaydet"))
        self.pushButton_5.setText(_translate("MainWindow", "Sil"))
        self.tabWidget_Cari.setTabText(self.tabWidget_Cari.indexOf(self.tab_CariKarti), _translate("MainWindow", "Cari Kartı"))
        self.tabWidget_Cari.setTabText(self.tabWidget_Cari.indexOf(self.tab_Hesap_Hareketleri), _translate("MainWindow", "Hesap Hareketleri"))
        self.groupBox.setTitle(_translate("MainWindow", "Notlar"))
        self.pushButton_Cari_Gorusme_Kaydet.setText(_translate("MainWindow", "Kaydet"))
        self.pushButton_Cari_Gorusme_Sil.setText(_translate("MainWindow", "Sil"))
        self.tabWidget_Cari.setTabText(self.tabWidget_Cari.indexOf(self.tab_Gorusme_Notlari), _translate("MainWindow", "Görüşme Notları"))
        self.subwindow_Stok_islemleri.setWindowTitle(_translate("MainWindow", "Stok İşlemleri"))
        self.groupBox_Cari_Kart_2.setTitle(_translate("MainWindow", "Stok"))
        self.label_15.setText(_translate("MainWindow", "Kodu"))
        self.lineEdit_Cari_Kodu_2.setPlaceholderText(_translate("MainWindow", "Kodu"))
        self.label_16.setText(_translate("MainWindow", "Adı"))
        self.lineEdit_Cari_Unvan_2.setPlaceholderText(_translate("MainWindow", "Ünvanı"))
        self.pushButton_6.setText(_translate("MainWindow", "Ara"))
        self.label_Cari_Durumu_2.setText(_translate("MainWindow", "&Durumu"))
        self.comboBox_Cari_Durum_2.setItemText(0, _translate("MainWindow", "Akrif"))
        self.comboBox_Cari_Durum_2.setItemText(1, _translate("MainWindow", "Pasif"))
        self.label_17.setText(_translate("MainWindow", "Stok Kart Listesi"))
        self.pushButton_Cari_Kart_Onceki_2.setText(_translate("MainWindow", "Önceki Kayıt"))
        self.pushButton_Cari_Kart_Sonraki_2.setText(_translate("MainWindow", "Sonraki Kayıt"))
        self.pushButton_7.setText(_translate("MainWindow", "Kaydet"))
        self.pushButton_8.setText(_translate("MainWindow", "Sil"))
        self.tabWidget_Stok.setTabText(self.tabWidget_Stok.indexOf(self.tab_Stok_Karti), _translate("MainWindow", "Stok Kartı"))
        self.tabWidget_Stok.setTabText(self.tabWidget_Stok.indexOf(self.tab_Stok_Ilave), _translate("MainWindow", "İlave Bilgiler"))
        self.menuFirma.setTitle(_translate("MainWindow", "Fir&ma"))
        self.menuUygulama_Yonetimi.setTitle(_translate("MainWindow", "&Uygulama Yönetimi"))
        self.menuYardim.setTitle(_translate("MainWindow", "&Yardım"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionFirma_Sec.setText(_translate("MainWindow", "&Firma Seç"))
        self.actionFirma_Kapat.setText(_translate("MainWindow", "Firma &Kapat"))
        self.action_Cik.setText(_translate("MainWindow", "&Çık"))
        self.actionKullanici_islemleri.setText(_translate("MainWindow", "&Kullanıcı İşlemleri"))
        self.actionFirma_islemleri.setText(_translate("MainWindow", "&Firma İşlemleri"))
        self.actionGenel_Tanimlamalar.setText(_translate("MainWindow", "&Genel Tanımlamalar"))
        self.actionGenel_Yardim.setText(_translate("MainWindow", "&Genel Yardım"))
        self.actionUygulama_Guncelleme.setText(_translate("MainWindow", "&Uygulama Güncelleme"))
        self.actionLisanslama.setText(_translate("MainWindow", "&Lisanslama"))
        self.actionYazilim_Firmasi_Hakkinda.setText(_translate("MainWindow", "&Yazılım Firması Hakkında"))
        self.actionCari_Hesaplar.setText(_translate("MainWindow", "Cari Hesaplar"))
        self.actionStok_islemleri.setText(_translate("MainWindow", "Stok İşlemleri"))
        self.actionRaporlar.setText(_translate("MainWindow", "Raporlar"))
        self.actionPencerleri_Yanyana_Sirala.setText(_translate("MainWindow", "Pencerleri Yanyana Sırala"))
        self.actionPencereleri_Ard_Arda_Sirala.setText(_translate("MainWindow", "Pencereleri Ard Arda Sırala"))
        self.actionSonraki_Pencere.setText(_translate("MainWindow", "Sonraki Pencere"))
        self.action_Onceki_Pencere.setText(_translate("MainWindow", "Önceki Pencere"))
        self.action_Cari_Gorusme_Kaydet.setText(_translate("MainWindow", "Kaydet"))
        self.action_Cari_Gorusme_Sil.setText(_translate("MainWindow", "Sil"))

import resources_rc
